/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlistmanager;

import javax.swing.JOptionPane;

/**
 *
 * @author Michael McCreary
 */
public class PlaylistGUI extends javax.swing.JFrame {

    /**
     * Creates new form PlaylistGUI
     */
    private PopPlaylist pop;
    private RockPlaylist rock;
    private LikedSongs likedSongs;
    private PlayListManager manager;

    public PlaylistGUI() {
        initComponents();
        pop = new PopPlaylist();
        rock = new RockPlaylist();
        likedSongs = new LikedSongs();
        manager = new PlayListManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        createPlaylist = new javax.swing.JButton();
        moveLastLikedSong = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        playlistGenre = new javax.swing.JComboBox<>();
        moveSongDown = new javax.swing.JButton();
        moveSongUp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        songName = new javax.swing.JTextField();
        songArtist = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        songGenre = new javax.swing.JComboBox<>();
        LikeSong = new javax.swing.JButton();
        displayPlaylist = new javax.swing.JButton();
        addToPlaylist = new javax.swing.JButton();
        displayLikedSongs = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createPlaylist.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        createPlaylist.setText("Create Playlist");
        createPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlaylistActionPerformed(evt);
            }
        });

        moveLastLikedSong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        moveLastLikedSong.setText("Move Last Liked Song To Playlist");
        moveLastLikedSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLastLikedSongActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete song");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Select Playlist");

        playlistGenre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        playlistGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Rock", "Pop" }));

        moveSongDown.setText("Move song down");
        moveSongDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveSongDownActionPerformed(evt);
            }
        });

        moveSongUp.setText("Move song up");
        moveSongUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveSongUpActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setText("Playlist Manager ");

        searchButton.setText("Search song ");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        songName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        songName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songNameActionPerformed(evt);
            }
        });

        songArtist.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        songArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songArtistActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Song Name");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Artist");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("Genre");

        songGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Rock", "Pop" }));
        songGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songGenreActionPerformed(evt);
            }
        });

        LikeSong.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LikeSong.setText("Like Song");
        LikeSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LikeSongActionPerformed(evt);
            }
        });

        displayPlaylist.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        displayPlaylist.setText("Display Playlist");
        displayPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPlaylistActionPerformed(evt);
            }
        });

        addToPlaylist.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addToPlaylist.setText("Add to playlist");
        addToPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToPlaylistActionPerformed(evt);
            }
        });

        displayLikedSongs.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        displayLikedSongs.setText("Display Liked Songs");
        displayLikedSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayLikedSongsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moveSongUp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moveSongDown))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(moveLastLikedSong, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(43, 43, 43)
                                            .addComponent(songName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(91, 91, 91)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(songArtist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(songGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(playlistGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LikeSong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addToPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayPlaylist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayLikedSongs, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(songName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LikeSong)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createPlaylist)
                            .addComponent(songArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addToPlaylist)
                            .addComponent(songGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveLastLikedSong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayLikedSongs))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayPlaylist)
                    .addComponent(playlistGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveSongDown)
                    .addComponent(moveSongUp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton)
                    .addComponent(searchButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlaylistActionPerformed
        // TODO add your handling code here:
//      Gets the Genre for the playlist based onnthe option selected by the user
        String genre = (String) songGenre.getSelectedItem();
        boolean isRepeat = false;
        boolean created = false;

        if (genre != null && !genre.trim().isEmpty()) {
//          check if the playlist alrerady exists
            if (manager.playlistExists(genre)) {
                JOptionPane.showMessageDialog(this, "A playlist for " + genre + " already exists. You can add songs to it.");
            } else {
//              if the playlist doesn't exist ask the user if they want to create it and if they want it to be repeated
                int repeat = JOptionPane.showConfirmDialog(this, "Do you want the " + genre + " playlist to play on repeat?", "Set Playlist Repeat", JOptionPane.YES_NO_OPTION);
                isRepeat = (repeat == JOptionPane.YES_OPTION);

//              create the playlist with the option for it to be repeated 
                PlaylistInterface newPlaylist = PlayListManager.PlaylistFactory.createPlaylist(genre);
                if (newPlaylist != null) {
                    newPlaylist.setIsRepeat(isRepeat);
//                  add the playlist to the playlist manager
                    created = manager.createAndAddPlaylist(genre, newPlaylist);
                    if (created) {
//                      Alert the user the playlist was created and they can add songs to it
                        JOptionPane.showMessageDialog(this, "Playlist for " + genre + " has been created, you can now add songs to it.");
                    }
                }
            }
        } else {
//           If the user does not select a genre, remind them they need to
            JOptionPane.showMessageDialog(this, "Please select a genre for your playlist.");
        }
    }//GEN-LAST:event_createPlaylistActionPerformed

    private void moveLastLikedSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLastLikedSongActionPerformed
        // TODO add your handling code here:
        likedSongs.moveSong();
        Song lastLikedSong = likedSongs.getLastLikedSong();

//   Check to see if there is any liked songs to move
        if (lastLikedSong == null) {
            JOptionPane.showMessageDialog(this, "There are no liked songs to move.");
            return;
        }

//      a lot of this code is copied from the create playlist button
        String genre = lastLikedSong.getGenre();
        boolean playlistExists = manager.playlistExists(genre);

//      Check if the playlist already exists
        if (!playlistExists) {
//        if it does not exist prompt the user to create it
            int create = JOptionPane.showConfirmDialog(this, "A playlist for " + genre + " doesn't exist. Do you want to create one?", "Create Playlist", JOptionPane.YES_NO_OPTION);
            if (create == JOptionPane.YES_OPTION) {
//            Ask if they want the new playlist to repeat.
                int repeat = JOptionPane.showConfirmDialog(this, "Do you want the " + genre + " playlist to play on repeat?", "Set Playlist Repeat", JOptionPane.YES_NO_OPTION);
                boolean isRepeat = (repeat == JOptionPane.YES_OPTION);

//             Create and add the new playlist
                PlaylistInterface newPlaylist = PlayListManager.PlaylistFactory.createPlaylist(genre);
                if (newPlaylist != null) {
                    newPlaylist.setIsRepeat(isRepeat);
                    manager.createAndAddPlaylist(genre, newPlaylist);
                    JOptionPane.showMessageDialog(this, "Playlist for " + genre + " created successfully.");
                    playlistExists = true;
                }
//           User chose not to create the playlist; exit early.
            } else {
                return;
            }
        }

//     If the playlist exists add the song to it.
        if (playlistExists) {
            PlaylistInterface targetPlaylist = manager.getPlaylist(genre);
            if (targetPlaylist != null) {
                targetPlaylist.addSong(lastLikedSong);
                JOptionPane.showMessageDialog(this, "Song moved to " + genre + " playlist successfully.");
            }
        }
    }//GEN-LAST:event_moveLastLikedSongActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String title = songName.getText();
        String genre = (String) playlistGenre.getSelectedItem();

//       Throws an error if the user does not enter a song or select a playlist
        if (title.isEmpty() || genre == null || genre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please ensure to input song name and select a playlist");
            return;
        }

//    get the playlist based on the users input
        PlaylistInterface playlist = manager.getPlaylist(genre);
        if (playlist == null) {
            JOptionPane.showMessageDialog(null, "The playlist for " + genre + " does not exist.");
            return;
        }

//  Call the delete method inside the playlist 
        playlist.deleteSong(title);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String title = songName.getText();
//      Display an error if the user does not enter a song name
        if (title == null || title.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid song in the song name field to search");
            return;
        }

//    String builder will be used to dispolay the results, be used if found in more than 1 playlist
        StringBuilder searchResults = new StringBuilder();
//    used to know if a song is found
        boolean found = false;

//     Search RRock and Pop Playlists
//      Iterate over each playlist managed by your PlayListManager
        for (String genre : manager.getAllPlaylistGenres()) {
            PlaylistInterface playlist = manager.getPlaylist(genre);
            for (Song song : playlist.search(title)) {
                if (song.getSong().equalsIgnoreCase(title.trim())) {
                    found = true;
                    searchResults.append("Found in ").append(genre).append(" playlist\n");
//                Stop searching this playlist if the song is found
                    break;
                }
            }
        }

        // Also, include the Liked Songs playlist in the search
        for (Song song : likedSongs.search(title)) {
            if (song.getSong().equalsIgnoreCase(title.trim())) {
                found = true;
                searchResults.append("Found in Liked Songs playlist\n");
                break;
            }
        }

//    Display Results
        if (found) {
            JOptionPane.showMessageDialog(null, "Song found in the following playlist(s):\n" + searchResults.toString());
        } else {
            JOptionPane.showMessageDialog(null, "This song is not in any of your playlists");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void songArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songArtistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songArtistActionPerformed

    private void LikeSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LikeSongActionPerformed
        // TODO add your handling code here:
//      If user leaves any options null it will throw an error message 
        if (songName.getText().trim().isEmpty() || songArtist.getText().trim().isEmpty() || songGenre.getSelectedItem().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please ensure to input song name, artist name and select a genre");
//       If all fields are filled in correctly add song to liked songs
        } else {
            String title = songName.getText();
            String artist = songArtist.getText();
            String genre = (String) songGenre.getSelectedItem();

            Song song = new Song(title, artist, genre);

            likedSongs.addSong(song);
        }
    }//GEN-LAST:event_LikeSongActionPerformed

    private void displayPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPlaylistActionPerformed
        // TODO add your handling code here:
        String genre = (String) playlistGenre.getSelectedItem();

//      If user leaves any options null it will throw an error message 
        if (genre == null || genre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select a playlist to display");
            return;
        }
        PlaylistInterface playlist = manager.getPlaylist(genre);

        // Check if a playlist exists for the selected genre
        if (playlist == null) {
            JOptionPane.showMessageDialog(null, "No playlist exists for " + genre);
        } else {
            // If the playlist exists, call its display method to show its contents
            playlist.display();
        }
    }//GEN-LAST:event_displayPlaylistActionPerformed

    private void songGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songGenreActionPerformed

    private void songNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songNameActionPerformed

    private void addToPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPlaylistActionPerformed
        // TODO add your handling code here:
//        Copied from liked songs button
        String title = songName.getText().trim();
        String artist = songArtist.getText().trim();
        String genre = (String) songGenre.getSelectedItem();

//        Copied from liked songs button
        if (title.isEmpty() || artist.isEmpty() || genre == null || genre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please ensure to input song name, artist name and select a genre.");
            return;
        }

        PlaylistInterface playlist = manager.getPlaylist(genre);

//        Copied from the cvreate playlist button
//        Check if the playlist exists
        if (playlist == null) {
//            Ask the user if they want to create the playlist since it doesn't exist
            int create = JOptionPane.showConfirmDialog(null, "The playlist for " + genre + " doesn't exist. Do you want to create one?", "Create Playlist", JOptionPane.YES_NO_OPTION);
            if (create == JOptionPane.YES_OPTION) {
//                Ask if the new playlist should be set to repeat
                int repeat = JOptionPane.showConfirmDialog(null, "Do you want the " + genre + " playlist to play on repeat?", "Set Playlist Repeat", JOptionPane.YES_NO_OPTION);
                boolean isRepeat = (repeat == JOptionPane.YES_OPTION);

//                Create the playlist based on the genre
                playlist = PlayListManager.PlaylistFactory.createPlaylist(genre);
                playlist.setIsRepeat(isRepeat);

//                Add the new playlist to the 
                manager.createAndAddPlaylist(genre, playlist);
            } else {
//                User chose not to create the playlist
                return;
            }
        }

//        add the song to the playlist
        Song newSong = new Song(title, artist, genre);
        playlist.addSong(newSong);
        JOptionPane.showMessageDialog(null, "Song added to " + genre + " playlist successfully.");
    }//GEN-LAST:event_addToPlaylistActionPerformed

    private void displayLikedSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayLikedSongsActionPerformed
        // TODO add your handling code here:

        likedSongs.displayLikedSongs();
    }//GEN-LAST:event_displayLikedSongsActionPerformed

    private void moveSongUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveSongUpActionPerformed
        // TODO add your handling code here:
        String genre = (String) playlistGenre.getSelectedItem();
        String title = songName.getText().trim();

//       If the user does not enter a song name or does not select a playlist
        if (title.isEmpty() || genre == null || genre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please ensure to enter song name and select a playlist");
            return;
        }

//  get the playlist based on users input
        PlaylistInterface playlist = manager.getPlaylist(genre);
        if (playlist == null) {
            JOptionPane.showMessageDialog(null, "The playlist for " + genre + " does not exist");
            return;
        }

//     move the song up the playlist
        playlist.moveUp(title);
    }//GEN-LAST:event_moveSongUpActionPerformed

//    Copid from the move song up button
    private void moveSongDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveSongDownActionPerformed
        // TODO add your handling code here:
        String genre = (String) playlistGenre.getSelectedItem();
        String title = songName.getText().trim();

//        If the user does not enter a song name or sselect a playlist, throw an error
        if (title.isEmpty() || genre == null || genre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter song name and select a playlist.");
            return;
        }

//       Get the playlist based on the users input 
        PlaylistInterface playlist = manager.getPlaylist(genre);
        if (playlist == null) {
            JOptionPane.showMessageDialog(null, "The playlist for " + genre + " does not exist.");
            return;
        }

//      move the song down the playlist
        playlist.moveDown(title);
    }//GEN-LAST:event_moveSongDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LikeSong;
    private javax.swing.JButton addToPlaylist;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton createPlaylist;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton displayLikedSongs;
    private javax.swing.JButton displayPlaylist;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton moveLastLikedSong;
    private javax.swing.JButton moveSongDown;
    private javax.swing.JButton moveSongUp;
    private javax.swing.JComboBox<String> playlistGenre;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField songArtist;
    private javax.swing.JComboBox<String> songGenre;
    private javax.swing.JTextField songName;
    // End of variables declaration//GEN-END:variables
}
