/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playlistmanager;

import javax.swing.JOptionPane;

/**
 *
 * @author Michael McCreary
 */
public class PlaylistGUI extends javax.swing.JFrame {

    /**
     * Creates new form PlaylistGUI
     */
    private PopPlaylist pop;
    private RockPlaylist rock;
    private LikedSongs likedSongs;
    private PlayListManager manager;

    public PlaylistGUI() {
        initComponents();
        pop = new PopPlaylist();
        rock = new RockPlaylist();
        likedSongs = new LikedSongs();
        manager = new PlayListManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        createPlaylist = new javax.swing.JButton();
        moveLastLikedSong = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        playlistGenre = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        songName = new javax.swing.JTextField();
        songArtist = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        songGenre = new javax.swing.JComboBox<>();
        LikeSong = new javax.swing.JButton();
        displayPlaylist = new javax.swing.JButton();
        playlistSong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addToPlaylist = new javax.swing.JButton();
        displayLikedSongs = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createPlaylist.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        createPlaylist.setText("Create Playlist");
        createPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlaylistActionPerformed(evt);
            }
        });

        moveLastLikedSong.setText("Move Last Liked Song To Playlist");
        moveLastLikedSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveLastLikedSongActionPerformed(evt);
            }
        });

        jButton4.setText("Delete song");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Select Playlist");

        playlistGenre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        playlistGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Rock", "Pop" }));

        jButton6.setText("Move song down");

        jButton7.setText("Move song up");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setText("Playlist Manager ");

        jButton8.setText("Search song ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        songName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        songName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songNameActionPerformed(evt);
            }
        });

        songArtist.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        songArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songArtistActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Song Name");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Artist");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("Genre");

        songGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Rock", "Pop" }));
        songGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songGenreActionPerformed(evt);
            }
        });

        LikeSong.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LikeSong.setText("Like Song");
        LikeSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LikeSongActionPerformed(evt);
            }
        });

        displayPlaylist.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        displayPlaylist.setText("Display Playlist");
        displayPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPlaylistActionPerformed(evt);
            }
        });

        playlistSong.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        playlistSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistSongActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setText("Song Name");

        addToPlaylist.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addToPlaylist.setText("Add to playlist");
        addToPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToPlaylistActionPerformed(evt);
            }
        });

        displayLikedSongs.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        displayLikedSongs.setText("Display Liked Songs");
        displayLikedSongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayLikedSongsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(songArtist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(songName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(songGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(playlistGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton6))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playlistSong, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(moveLastLikedSong, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(37, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LikeSong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addToPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayLikedSongs))
                                .addGap(30, 30, 30))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LikeSong)
                        .addGap(27, 27, 27)
                        .addComponent(createPlaylist)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addToPlaylist)
                            .addComponent(jLabel4)
                            .addComponent(songArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(songName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayPlaylist)
                    .addComponent(songGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayLikedSongs)
                    .addComponent(jLabel5)
                    .addComponent(playlistGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveLastLikedSong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playlistSong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton4)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlaylistActionPerformed
        // TODO add your handling code here:
//      Gets the Genre for the playlist based onnthe option selected by the user
        String genre = (String) songGenre.getSelectedItem();
        boolean isRepeat = false;
        boolean created = false;

        if (genre != null && !genre.trim().isEmpty()) {
//          check if the playlist alrerady exists
            if (manager.playlistExists(genre)) {
                JOptionPane.showMessageDialog(this, "A playlist for " + genre + " already exists. You can add songs to it.");
            } else {
//              if the playlist doesn't exist ask the user if they want to create it and if they want it to be repeated
                int repeat = JOptionPane.showConfirmDialog(this, "Do you want the " + genre + " playlist to play on repeat?", "Set Playlist Repeat", JOptionPane.YES_NO_OPTION);
                isRepeat = (repeat == JOptionPane.YES_OPTION);

//              create the playlist with the option for it to be repeated 
                PlaylistInterface newPlaylist = PlayListManager.PlaylistFactory.createPlaylist(genre);
                if (newPlaylist != null) {
                    newPlaylist.setIsRepeat(isRepeat);
//                  add the playlist to the playlist manager
                    created = manager.createAndAddPlaylist(genre, newPlaylist);
                    if (created) {
//                      Alert the user the playlist was created and they can add songs to it
                        JOptionPane.showMessageDialog(this, "Playlist for " + genre + " has been created, you can now add songs to it.");
                    }
                }
            }
        } else {
//           If the user does not select a genre, remind them they need to
            JOptionPane.showMessageDialog(this, "Please select a genre for your playlist.");
        }
    }//GEN-LAST:event_createPlaylistActionPerformed

    private void moveLastLikedSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveLastLikedSongActionPerformed
        // TODO add your handling code here:
        likedSongs.moveSong();
        Song lastLikedSong = likedSongs.getLastLikedSong();

//   Check to see if there is any liked songs to move
        if (lastLikedSong == null) {
            JOptionPane.showMessageDialog(this, "There are no liked songs to move.");
            return;
        }
        
//      a lot of this code is copied from the create playlist button
        String genre = lastLikedSong.getGenre();
        boolean playlistExists = manager.playlistExists(genre);

//      Check if the playlist already exists
        if (!playlistExists) {
//        if it does not exist prompt the user to create it
            int create = JOptionPane.showConfirmDialog(this, "A playlist for " + genre + " doesn't exist. Do you want to create one?", "Create Playlist", JOptionPane.YES_NO_OPTION);
            if (create == JOptionPane.YES_OPTION) {
//            Ask if they want the new playlist to repeat.
                int repeat = JOptionPane.showConfirmDialog(this, "Do you want the " + genre + " playlist to play on repeat?", "Set Playlist Repeat", JOptionPane.YES_NO_OPTION);
                boolean isRepeat = (repeat == JOptionPane.YES_OPTION);

//             Create and add the new playlist
                PlaylistInterface newPlaylist = PlayListManager.PlaylistFactory.createPlaylist(genre);
                if (newPlaylist != null) {
                    newPlaylist.setIsRepeat(isRepeat);
                    manager.createAndAddPlaylist(genre, newPlaylist);
                    JOptionPane.showMessageDialog(this, "Playlist for " + genre + " created successfully.");
                    playlistExists = true;
                } else {
                    JOptionPane.showMessageDialog(this, "There was an issue creating the playlist. Please try again.");
                    return; 
                }
//           User chose not to create the playlist; exit early.
            } else {
                return; 
            }
        }
    
//     If the playlist exists add the song to it.
    if (playlistExists) {
        PlaylistInterface targetPlaylist = manager.getPlaylist(genre);
        if (targetPlaylist != null) {
            targetPlaylist.addSong(lastLikedSong);
            JOptionPane.showMessageDialog(this, "Song moved to " + genre + " playlist successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Error: Could not retrieve the " + genre + " playlist.");
        }
    }
    }//GEN-LAST:event_moveLastLikedSongActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void songArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songArtistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songArtistActionPerformed

    private void LikeSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LikeSongActionPerformed
        // TODO add your handling code here:
//      If user leaves any options null it will throw an error message 
        if (songName.getText().trim().isEmpty() || songArtist.getText().trim().isEmpty() || songGenre.getSelectedItem().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please ensure to input song name, artist name and select a genre");
//       If all fields are filled in correctly add song to liked songs
        } else {
            String title = songName.getText();
            String artist = songArtist.getText();
            String genre = (String) songGenre.getSelectedItem();

            Song song = new Song(title, artist, genre);

            likedSongs.addSong(song);
        }
    }//GEN-LAST:event_LikeSongActionPerformed

    private void displayPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayPlaylistActionPerformed

    private void songGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songGenreActionPerformed

    private void playlistSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playlistSongActionPerformed

    private void songNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songNameActionPerformed

    private void addToPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToPlaylistActionPerformed

    private void displayLikedSongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayLikedSongsActionPerformed
        // TODO add your handling code here:

        likedSongs.displayLikedSongs();
    }//GEN-LAST:event_displayLikedSongsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LikeSong;
    private javax.swing.JButton addToPlaylist;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton createPlaylist;
    private javax.swing.JButton displayLikedSongs;
    private javax.swing.JButton displayPlaylist;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton moveLastLikedSong;
    private javax.swing.JComboBox<String> playlistGenre;
    private javax.swing.JTextField playlistSong;
    private javax.swing.JTextField songArtist;
    private javax.swing.JComboBox<String> songGenre;
    private javax.swing.JTextField songName;
    // End of variables declaration//GEN-END:variables
}
